name: Build and Deploy Localization

on:
  workflow_dispatch: # Дозволяє запускати вручну з вкладки Actions

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # ЄДИНИЙ КРОК ДЛЯ АКТИВАЦІЇ ТА ЗБІРКИ
      - name: Build Localization Content with Unity
        uses: game-ci/unity-builder@v4
        with:
          unityVersion: 6000.2.1f1 # Ваша версія Unity
          targetPlatform: StandaloneLinux64
          # Автентифікація передається прямо сюди
          unityEmail: ${{ secrets.UNITY_EMAIL }}
          unityPassword: ${{ secrets.UNITY_PASSWORD }}
          # Інші параметри
          customParameters: -projectPath . -executeMethod BuildAutomation.BuildLocalization -nographics

      # КРОК ДЕПЛОЮ (залишається без змін)
      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_MY_GAME_LOCALIZATION }}'
          projectId: localization-system-4a5c3
          entryPoint: ServerData/StandaloneLinux64