name: Build and Deploy Localization

on:
  workflow_dispatch: # Дозволяє запускати вручну з вкладки Actions

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # КРОК 1: АКТИВАЦІЯ UNITY (виправлена назва екшену)
      - name: Activate Unity License
        id: activate
        uses: game-ci/unity-activate@v2 # <-- ПРАВИЛЬНА НАЗВА
        with:
          email: ${{ secrets.UNITY_EMAIL }}
          password: ${{ secrets.UNITY_PASSWORD }}
          
      # КРОК 2: ЗБІРКА КОНТЕНТУ
      - name: Build Localization Content with Unity
        uses: game-ci/unity-builder@v4
        env:
          # Використовуємо правильний вивід "license"
          UNITY_LICENSE: ${{ steps.activate.outputs.license }} # <-- ПРАВИЛЬНА НАЗВА ВИВОДУ
        with:
          unityVersion: 6000.2.1f1 # Ваша версія Unity
          targetPlatform: StandaloneLinux64
          customParameters: -projectPath . -executeMethod BuildAutomation.BuildLocalization

      # КРОК 3: ДЕПЛОЙ НА FIREBASE
      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_MY_GAME_LOCALIZATION }}'
          projectId: localization-system-4a5c3
          entryPoint: ServerData/StandaloneLinux64